slider_mapping:
  0: master
  1: Spotify.exe
  2: deej.current  
  3: discord.exe

com_port: COM5

baud_rate: 9600

noise_reduction: default

button_mapping:
  0: mute_master
  1: media_play_pause
  2: media_previous
  3: media_next
